# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-05 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfoIdol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('birthday', models.DateTimeField()),
                ('height', models.PositiveIntegerField()),
                ('v1', models.PositiveIntegerField()),
                ('v2', models.PositiveIntegerField()),
                ('v3', models.PositiveIntegerField()),
                ('list_film', models.TextField()),
            ],
        ),
    ]
