# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-05 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_idol', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoidol',
            name='birthday',
            field=models.DateField(),
        ),
    ]
